from sqlalchemy import Column, Integer, String, DateTime, Text, JSON, Boolean
from sqlalchemy.sql import func
from apps.api.db.database import Base

class KnowledgeBase(Base):
    """
    Stores the latest structured business intelligence extracted from the official SETV website.
    """
    __tablename__ = "setv_knowledge_base"

    id = Column(Integer, primary_key=True, index=True)
    version = Column(Integer, default=1, nullable=False)
    data = Column(JSON, nullable=False)  # The extracted structured JSON
    raw_hash = Column(String, nullable=True) # Optional hash to detect if raw text changed before parsing
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())


class KnowledgeSyncLog(Base):
    """
    Logs every sync execution, the pages crawled, and any changes detected.
    """
    __tablename__ = "setv_knowledge_sync_logs"

    id = Column(Integer, primary_key=True, index=True)
    sync_time = Column(DateTime(timezone=True), server_default=func.now())
    pages_crawled = Column(JSON, nullable=True) # List of URLs
    changes_detected = Column(JSON, nullable=True) # Diff summary generated by LLM
    knowledge_version = Column(Integer, nullable=True)
    status = Column(String, default="success") # success, failed
    errors = Column(Text, nullable=True)
