"""add outreach templates

Revision ID: 2d19009da3a9
Revises: 6524af96a383
Create Date: 2026-07-29 16:24:13.672528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d19009da3a9'
down_revision: Union[str, None] = '6524af96a383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_templates_name'), ['name'], unique=False)



    with op.batch_alter_table('agent_settings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'outreach_templates', ['default_outreach_template_id'], ['id'])

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'outreach_templates', ['outreach_template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('agent_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')


    with op.batch_alter_table('outreach_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_templates_name'))
        batch_op.drop_index(batch_op.f('ix_outreach_templates_id'))
        batch_op.drop_index(batch_op.f('ix_outreach_templates_category'))

    op.drop_table('outreach_templates')
    # ### end Alembic commands ###
