"""Restore missing tables

Revision ID: 408a6fdfb119
Revises: 607232b1297a
Create Date: 2026-07-15 20:37:02.398295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408a6fdfb119'
down_revision: Union[str, None] = '607232b1297a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('window_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_type', 'entity_id', 'window_key', name='uq_idempotency')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_records_job_type'), ['job_type'], unique=False)

    op.create_table('prospecting_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('icp_json', sa.Text(), nullable=True),
    sa.Column('total_companies_discovered', sa.Integer(), nullable=True),
    sa.Column('total_leads_qualified', sa.Integer(), nullable=True),
    sa.Column('total_leads_persisted', sa.Integer(), nullable=True),
    sa.Column('provider_stats_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prospecting_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prospecting_jobs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospecting_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prospecting_jobs_id'))

    op.drop_table('prospecting_jobs')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_job_type'))
        batch_op.drop_index(batch_op.f('ix_idempotency_records_id'))
        batch_op.drop_index(batch_op.f('ix_idempotency_records_entity_id'))

    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
