"""Upgrade signals table

Revision ID: 607232b1297a
Revises: ce618f1237ab
Create Date: 2026-07-15 20:29:00.206347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '607232b1297a'
down_revision: Union[str, None] = 'ce618f1237ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index('ix_idempotency_records_entity_id')
        batch_op.drop_index('ix_idempotency_records_id')
        batch_op.drop_index('ix_idempotency_records_job_type')

    op.drop_table('idempotency_records')
    with op.batch_alter_table('google_oauth_credentials', schema=None) as batch_op:
        batch_op.drop_index('ix_google_oauth_credentials_email')
        batch_op.drop_index('ix_google_oauth_credentials_id')
        batch_op.drop_index('ix_google_oauth_credentials_user_id')

    op.drop_table('google_oauth_credentials')
    with op.batch_alter_table('prospecting_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_prospecting_jobs_id')

    op.drop_table('prospecting_jobs')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signal_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('headline', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('business_impact', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('why_it_matters', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('source_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('published_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_contribution', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recommended_action', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('suggested_pitch', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('target_persona', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('icp_match', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('type')
        batch_op.drop_column('strength')
        batch_op.drop_column('evidence_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('icp_match')
        batch_op.drop_column('target_persona')
        batch_op.drop_column('suggested_pitch')
        batch_op.drop_column('recommended_action')
        batch_op.drop_column('score_contribution')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('published_date')
        batch_op.drop_column('source_type')
        batch_op.drop_column('source_url')
        batch_op.drop_column('source_name')
        batch_op.drop_column('why_it_matters')
        batch_op.drop_column('business_impact')
        batch_op.drop_column('headline')
        batch_op.drop_column('signal_type')

    op.create_table('prospecting_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icp_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_companies_discovered', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_leads_qualified', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_leads_persisted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_stats_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='prospecting_jobs_pkey')
    )
    with op.batch_alter_table('prospecting_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_prospecting_jobs_id', ['id'], unique=False)

    op.create_table('google_oauth_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='google_oauth_credentials_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='google_oauth_credentials_pkey')
    )
    with op.batch_alter_table('google_oauth_credentials', schema=None) as batch_op:
        batch_op.create_index('ix_google_oauth_credentials_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_google_oauth_credentials_id', ['id'], unique=False)
        batch_op.create_index('ix_google_oauth_credentials_email', ['email'], unique=True)

    op.create_table('idempotency_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('window_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='idempotency_records_pkey'),
    sa.UniqueConstraint('job_type', 'entity_id', 'window_key', name='uq_idempotency')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index('ix_idempotency_records_job_type', ['job_type'], unique=False)
        batch_op.create_index('ix_idempotency_records_id', ['id'], unique=False)
        batch_op.create_index('ix_idempotency_records_entity_id', ['entity_id'], unique=False)

    # ### end Alembic commands ###
