"""Expand meetings table with full CRM fields

Revision ID: 6a9f501c6559
Revises: 408a6fdfb119
Create Date: 2026-07-15 21:51:38.919647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a9f501c6559'
down_revision: Union[str, None] = '408a6fdfb119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_oauth_credentials', schema=None) as batch_op:
        batch_op.drop_index('ix_google_oauth_credentials_email')
        batch_op.drop_index('ix_google_oauth_credentials_id')
        batch_op.drop_index('ix_google_oauth_credentials_user_id')

    op.drop_table('google_oauth_credentials')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('google_event_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('meet_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('organizer_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('attendee_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('calendar_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['google_event_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('calendar_status')
        batch_op.drop_column('attendee_email')
        batch_op.drop_column('organizer_email')
        batch_op.drop_column('meet_link')
        batch_op.drop_column('google_event_id')
        batch_op.drop_column('timezone')
        batch_op.drop_column('end_time')
        batch_op.drop_column('description')
        batch_op.drop_column('lead_name')

    op.create_table('google_oauth_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='google_oauth_credentials_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='google_oauth_credentials_pkey')
    )
    with op.batch_alter_table('google_oauth_credentials', schema=None) as batch_op:
        batch_op.create_index('ix_google_oauth_credentials_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_google_oauth_credentials_id', ['id'], unique=False)
        batch_op.create_index('ix_google_oauth_credentials_email', ['email'], unique=True)

    # ### end Alembic commands ###
