"""Add JobTemplate fields

Revision ID: 9516d420f16b
Revises: a1df3c018fc3
Create Date: 2026-07-17 18:09:29.779382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9516d420f16b'
down_revision: Union[str, None] = 'a1df3c018fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_oauth_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_oauth_credentials_email'))
        batch_op.drop_index(batch_op.f('ix_google_oauth_credentials_id'))
        batch_op.drop_index(batch_op.f('ix_google_oauth_credentials_user_id'))

    op.drop_table('google_oauth_credentials')
    with op.batch_alter_table('job_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regions', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company_size_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('company_size_max', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_templates', schema=None) as batch_op:
        batch_op.drop_column('company_size_max')
        batch_op.drop_column('company_size_min')
        batch_op.drop_column('regions')

    op.create_table('google_oauth_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('google_oauth_credentials_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('google_oauth_credentials_pkey'))
    )
    with op.batch_alter_table('google_oauth_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_oauth_credentials_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_google_oauth_credentials_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_google_oauth_credentials_email'), ['email'], unique=True)

    # ### end Alembic commands ###
