"""Add Auto Agent Settings and Job Templates

Revision ID: a1df3c018fc3
Revises: 6a9f501c6559
Create Date: 2026-07-16 22:45:59.569959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1df3c018fc3'
down_revision: Union[str, None] = '6a9f501c6559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('default_template_id', sa.Integer(), nullable=True),
    sa.Column('auto_send_emails', sa.Boolean(), nullable=True),
    sa.Column('max_leads_per_run', sa.Integer(), nullable=True),
    sa.Column('daily_email_limit', sa.Integer(), nullable=True),
    sa.Column('reply_monitoring', sa.Boolean(), nullable=True),
    sa.Column('working_hours', sa.String(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_settings_id'), ['id'], unique=False)

    op.create_table('job_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industries', sa.String(), nullable=True),
    sa.Column('target_roles', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('technologies', sa.String(), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_templates_id'), ['id'], unique=False)

    with op.batch_alter_table('google_oauth_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_oauth_credentials_email'))
        batch_op.drop_index(batch_op.f('ix_google_oauth_credentials_id'))
        batch_op.drop_index(batch_op.f('ix_google_oauth_credentials_user_id'))

    op.drop_table('google_oauth_credentials')
    with op.batch_alter_table('prospecting_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_used_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('outreach_generated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('emails_sent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('execution_logs', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospecting_jobs', schema=None) as batch_op:
        batch_op.drop_column('execution_logs')
        batch_op.drop_column('emails_sent')
        batch_op.drop_column('outreach_generated')
        batch_op.drop_column('template_used_id')

    op.create_table('google_oauth_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('google_oauth_credentials_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('google_oauth_credentials_pkey'))
    )
    with op.batch_alter_table('google_oauth_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_oauth_credentials_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_google_oauth_credentials_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_google_oauth_credentials_email'), ['email'], unique=True)

    with op.batch_alter_table('job_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_templates_id'))

    op.drop_table('job_templates')
    with op.batch_alter_table('agent_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_settings_id'))

    op.drop_table('agent_settings')
    # ### end Alembic commands ###
