"""Sync Postgres

Revision ID: ce618f1237ab
Revises: 
Create Date: 2026-07-15 20:00:06.539444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce618f1237ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('objections', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('reply_draft', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reply_id')
    )
    with op.batch_alter_table('reply_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reply_analyses_id'), ['id'], unique=False)

    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index('ix_idempotency_records_entity_id')
        batch_op.drop_index('ix_idempotency_records_id')
        batch_op.drop_index('ix_idempotency_records_job_type')

    op.drop_table('idempotency_records')
    with op.batch_alter_table('prospecting_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_prospecting_jobs_id')

    op.drop_table('prospecting_jobs')
    with op.batch_alter_table('google_oauth_credentials', schema=None) as batch_op:
        batch_op.drop_index('ix_google_oauth_credentials_email')
        batch_op.drop_index('ix_google_oauth_credentials_id')
        batch_op.drop_index('ix_google_oauth_credentials_user_id')

    op.drop_table('google_oauth_credentials')
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gmail_message_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sender_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sender_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('raw_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('clean_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['gmail_message_id'])
        batch_op.drop_column('sentiment')
        batch_op.drop_column('intent')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intent', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sentiment', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_archived')
        batch_op.drop_column('clean_body')
        batch_op.drop_column('raw_body')
        batch_op.drop_column('subject')
        batch_op.drop_column('sender_name')
        batch_op.drop_column('sender_email')
        batch_op.drop_column('gmail_message_id')
        batch_op.drop_column('thread_id')

    op.create_table('google_oauth_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='google_oauth_credentials_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='google_oauth_credentials_pkey')
    )
    with op.batch_alter_table('google_oauth_credentials', schema=None) as batch_op:
        batch_op.create_index('ix_google_oauth_credentials_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_google_oauth_credentials_id', ['id'], unique=False)
        batch_op.create_index('ix_google_oauth_credentials_email', ['email'], unique=True)

    op.create_table('prospecting_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icp_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_companies_discovered', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_leads_qualified', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_leads_persisted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_stats_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='prospecting_jobs_pkey')
    )
    with op.batch_alter_table('prospecting_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_prospecting_jobs_id', ['id'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('window_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='idempotency_records_pkey'),
    sa.UniqueConstraint('job_type', 'entity_id', 'window_key', name='uq_idempotency')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index('ix_idempotency_records_job_type', ['job_type'], unique=False)
        batch_op.create_index('ix_idempotency_records_id', ['id'], unique=False)
        batch_op.create_index('ix_idempotency_records_entity_id', ['entity_id'], unique=False)

    with op.batch_alter_table('reply_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reply_analyses_id'))

    op.drop_table('reply_analyses')
    # ### end Alembic commands ###
